# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LPlSuZ-2Vku_FboCcmPc-FmWPBYRaqvn
"""

# Commented out IPython magic to ensure Python compatibility.
# ALGORITMO K-VECINOS MÁS CERCANOS (KNN)
# Se accede a las carpetas de Google drive
from google.colab import drive
drive.mount('/content/drive')

# Se habilita entrada de código
from ast import Mult

# Se habilitan gráficos dentro de Jupyter Notebook
# %matplotlib inline

import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Se accede al archivo CSV
heave_train = '/content/drive/MyDrive/port_coruna/heave_train.csv'
df = pd.read_csv(heave_train)
x = df[['h_s', 't_p', 'dir', 'wind_speed', 'wind_dir', 'h_0', 'h_sm', 'length', 'breath']]
y = df[['mov_avg','mov_max','mov_sig']]

model = KNeighborsRegressor()
model.fit(x, y)
prediction_knn = model.predict(x)
r2 = r2_score(y, prediction_knn)
plt.scatter(y, prediction_knn)
plt.xlabel('Oscilación vertical lineal de la embarcación (real)')
plt.ylabel('Oscilación vertical lineal de la embarcación (Predicción)')
plt.show()
print("Número de vecinos obtenido:", model.n_neighbors)
print(r2)

# Commented out IPython magic to ensure Python compatibility.
# Se accede a las carpetas de Google drive
from google.colab import drive
drive.mount('/content/drive')

# Se habilita entrada de código
from ast import Mult

# Se habilitan gráficos dentro de Jupyter Notebook
# %matplotlib inline


import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Se accede al archivo CSV
yaw_train = '/content/drive/MyDrive/port_coruna/yaw_train.csv'
df = pd.read_csv(yaw_train)
x = df[['h_s', 't_p', 'dir', 'wind_speed', 'wind_dir', 'h_0', 'h_sm', 'length', 'breath']]
y = df[['mov_avg','mov_max','mov_sig']]

model = KNeighborsRegressor()
model.fit(x, y)
prediction_knn = model.predict(x)
r2 = r2_score(y, prediction_knn)
plt.scatter(y, prediction_knn)
plt.xlabel('Guiñada de la embarcación (real)')
plt.ylabel('Guiñada de la embarcación (Predicción)')
plt.show()
print("Número de vecinos obtenido:", model.n_neighbors)
print(r2)

# Commented out IPython magic to ensure Python compatibility.
# Se accede a las carpetas de Google drive
from google.colab import drive
drive.mount('/content/drive')

# Se habilita entrada de código
from ast import Mult

# Se habilitan gráficos dentro de Jupyter Notebook
# %matplotlib inline


import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Se accede al archivo CSV
surge_train = '/content/drive/MyDrive/port_coruna/surge_train.csv'
df = pd.read_csv(surge_train)
x = df[['h_s', 't_p', 'dir', 'wind_speed', 'wind_dir', 'h_0', 'h_sm', 'length', 'breath']]
y = df[['mov_avg','mov_max','mov_sig']]

model = KNeighborsRegressor()
model.fit(x, y)
prediction_knn = model.predict(x)
r2 = r2_score(y, prediction_knn)
plt.scatter(y, prediction_knn)
plt.xlabel('Marejada de la embarcación (real)')
plt.ylabel('Marejada de la embarcación (Predicción)')
plt.show()
print("Número de vecinos obtenido:", model.n_neighbors)
print(r2)

# Commented out IPython magic to ensure Python compatibility.
# Se accede a las carpetas de Google drive
from google.colab import drive
drive.mount('/content/drive')

# Se habilita entrada de código
from ast import Mult

# Se habilitan gráficos dentro de Jupyter Notebook
# %matplotlib inline


import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Se accede al archivo CSV
roll_train = '/content/drive/MyDrive/port_coruna/roll_train.csv'
df = pd.read_csv(roll_train)
x = df[['h_s', 't_p', 'dir', 'wind_speed', 'wind_dir', 'h_0', 'h_sm', 'length', 'breath']]
y = df[['mov_avg','mov_max','mov_sig']]

model = KNeighborsRegressor()
model.fit(x, y)
prediction_knn = model.predict(x)
r2 = r2_score(y, prediction_knn)
plt.scatter(y, prediction_knn)
plt.xlabel('Balanceo o Escora de la embarcación (real)')
plt.ylabel('Balanceo o Escora de la embarcación (Predicción)')
plt.show()
print("Número de vecinos obtenido:", model.n_neighbors)
print(r2)

# Commented out IPython magic to ensure Python compatibility.
# Se accede a las carpetas de Google drive
from google.colab import drive
drive.mount('/content/drive')

# Se habilita entrada de código
from ast import Mult

# Se habilitan gráficos dentro de Jupyter Notebook
# %matplotlib inline

import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Se accede al archivo CSV
sway_train = '/content/drive/MyDrive/port_coruna/sway_train.csv'
df = pd.read_csv(sway_train)
df.dropna(inplace = True)
x = df[['h_s', 't_p', 'dir', 'wind_speed', 'wind_dir', 'h_0', 'h_sm', 'length', 'breath']]
y = df[['mov_avg','mov_max','mov_sig']]


model = KNeighborsRegressor()
model.fit(x, y)
prediction_knn = model.predict(x)
r2 = r2_score(y, prediction_knn)
plt.scatter(y, prediction_knn)
plt.xlabel('Balanceo lateral lineal de la embarcación (real)')
plt.ylabel('Balanceo lateral lineal de la embarcación (Predicción)')
plt.show()
print("Número de vecinos obtenido:", model.n_neighbors)
print(r2)

# Commented out IPython magic to ensure Python compatibility.
# Se accede a las carpetas de Google drive
from google.colab import drive
drive.mount('/content/drive')

# Se habilita entrada de código
from ast import Mult

# Se habilitan gráficos dentro de Jupyter Notebook
# %matplotlib inline

import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Se accede al archivo CSV
pitch_train = '/content/drive/MyDrive/port_coruna/pitch_train.csv'
df = pd.read_csv(pitch_train)
x = df[['h_s', 't_p', 'dir', 'wind_speed', 'wind_dir', 'h_0', 'h_sm', 'length', 'breath']]
y = df[['mov_avg','mov_max','mov_sig']]

model = KNeighborsRegressor()
model.fit(x, y)
prediction_knn = model.predict(x)
r2 = r2_score(y, prediction_knn)
plt.scatter(y, prediction_knn)
plt.xlabel('Cabeceo ascendente/descendente eje lateral buque (real)')
plt.ylabel('Cabeceo ascendente/descendente eje lateral buque (Predicción)')
plt.show()
print("Número de vecinos obtenido:", model.n_neighbors)
print(r2)