# -*- coding: utf-8 -*-
"""Random Forest_train.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oPebf324v8Zu0tyuec3SYxd7ZUnJNy1Q
"""

# Commented out IPython magic to ensure Python compatibility.
# ALGORITMO DE RANDOM FOREST
# Se accede a las carpetas de Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Se habilita entrada de código
from ast import Mult

# Se habilitan gráficos dentro de Jupyter Notebook
# %matplotlib inline

import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Se accede al archivo CSV
heave_train = '/content/drive/MyDrive/port_coruna/heave_train.csv'
df = pd.read_csv(heave_train)
x = df[['h_s', 't_p', 'dir', 'wind_speed', 'wind_dir', 'h_0', 'h_sm', 'length', 'breath']]
y = df[['mov_avg', 'mov_max', 'mov_sig']]

model = RandomForestRegressor()
model.fit(x, y)
prediction_rf = model.predict(x)
r2 = r2_score(y, prediction_rf)
plt.scatter(y, prediction_rf)
plt.xlabel('Oscilación vertical lineal de la embarcación (real)')
plt.ylabel('Oscilación vertical lineal de la embarcación (Predicción)')
plt.show()
print("Número de árboles en el bosque:", model.n_estimators)
print(r2)



# Commented out IPython magic to ensure Python compatibility.

# Se accede a las carpetas de Google Drive y se habilta la entrada de código
from google.colab import drive
drive.mount('/content/drive')
from ast import Mult
# Se habilitan gráficos dentro de Jupyter Notebook
# %matplotlib inline

# Se importan las librerías para el acceso al dataset
import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Se accede al archivo CSV
yaw_train = '/content/drive/MyDrive/port_coruna/yaw_train.csv'
df = pd.read_csv(yaw_train)
x = df[['h_s', 't_p', 'dir', 'wind_speed', 'wind_dir', 'h_0', 'h_sm', 'length', 'breath']]
y = df[['mov_avg','mov_max','mov_sig']]

# Se crea la instancia (objeto específico del modelo) y se ajusta el modelo a los datos
model = RandomForestRegressor()
model.fit(x, y)
prediction_rf = model.predict(x)
r2 = r2_score(y, prediction_rf)

# Se realizan predicciones del modelo y se muestra

plt.scatter(y, prediction_rf)
plt.xlabel('Guiñada de la embarcación (real)')
plt.ylabel('Guiñada de la embarcación (Predicción)')
plt.show()
print("Número de árboles en el bosque:", model.n_estimators)
print(r2)

# Commented out IPython magic to ensure Python compatibility.
# Se accede a las carpetas de Google Drive y se habilta la entrada de código
from google.colab import drive
drive.mount('/content/drive')
from ast import Mult
# Se habilitan gráficos dentro de Jupyter Notebook
# %matplotlib inline

# Se importan las librerías para el acceso al dataset
import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Se accede al archivo CSV
surge_train = '/content/drive/MyDrive/port_coruna/surge_train.csv'
df = pd.read_csv(surge_train)
x = df[['h_s', 't_p', 'dir', 'wind_speed', 'wind_dir', 'h_0', 'h_sm', 'length', 'breath']]
y = df[['mov_avg','mov_max','mov_sig']]

# Se crea la instancia (objeto específico del modelo) y se ajusta el modelo a los datos
model = RandomForestRegressor()
model.fit(x, y)
prediction_rf = model.predict(x)
r2 = r2_score(y, prediction_rf)

# Se realizan predicciones del modelo y se muestra

plt.scatter(y, prediction_rf)
plt.xlabel('Marejada de la embarcación (real)')
plt.ylabel('Marejada de la embarcación (Predicción)')
plt.show()
print("Número de árboles en el bosque:", model.n_estimators)
print(r2)

# Commented out IPython magic to ensure Python compatibility.
# Se accede a las carpetas de Google Drive y se habilta la entrada de código
from google.colab import drive
drive.mount('/content/drive')
from ast import Mult
# Se habilitan gráficos dentro de Jupyter Notebook
# %matplotlib inline

# Se importan las librerías para el acceso al dataset
import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Se accede al archivo CSV
roll_train = '/content/drive/MyDrive/port_coruna/roll_train.csv'
df = pd.read_csv(roll_train)
x = df[['h_s', 't_p', 'dir', 'wind_speed', 'wind_dir', 'h_0', 'h_sm', 'length', 'breath']]
y = df[['mov_avg','mov_max','mov_sig']]

# Se crea la instancia (objeto específico del modelo) y se ajusta el modelo a los datos
model = RandomForestRegressor()
model.fit(x, y)
prediction_rf = model.predict(x)
r2 = r2_score(y, prediction_rf)

# Se realizan predicciones del modelo y se muestra

plt.scatter(y, prediction_rf)
plt.xlabel('Escora o Balanceo de la embarcación (real)')
plt.ylabel('Escora o Balanceo de la embarcación (Predicción)')
plt.show()
print("Número de árboles en el bosque:", model.n_estimators)
print(r2)

# Commented out IPython magic to ensure Python compatibility.
# Se accede a las carpetas de Google Drive y se habilta la entrada de código
from google.colab import drive
drive.mount('/content/drive')
from ast import Mult
# Se habilitan gráficos dentro de Jupyter Notebook
# %matplotlib inline

# Se importan las librerías para el acceso al dataset
import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Se accede al archivo CSV
sway_train = '/content/drive/MyDrive/port_coruna/sway_train.csv'
df = pd.read_csv(sway_train)
df.dropna(inplace = True)
x = df[['h_s', 't_p', 'dir', 'wind_speed', 'wind_dir', 'h_0', 'h_sm', 'length', 'breath']]
y = df[['mov_avg','mov_max','mov_sig']]

# Se crea la instancia (objeto específico del modelo) y se ajusta el modelo a los datos
model = RandomForestRegressor()
model.fit(x, y)
prediction_rf = model.predict(x)
r2 = r2_score(y, prediction_rf)

# Se realizan predicciones del modelo y se muestra

plt.scatter(y, prediction_rf)
plt.xlabel('Abatimiento / Ronza (Traslación Eje Y)de la embarcación (real)')
plt.ylabel('Abatimiento / Ronza (Traslación Eje Y) de la embarcación (Predicción)')
plt.show()
print("Número de árboles en el bosque:", model.n_estimators)
print(r2)

# Commented out IPython magic to ensure Python compatibility.
# Se accede a las carpetas de Google Drive y se habilta la entrada de código
from google.colab import drive
drive.mount('/content/drive')
from ast import Mult
# Se habilitan gráficos dentro de Jupyter Notebook
# %matplotlib inline

# Se importan las librerías para el acceso al dataset
import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Se accede al archivo CSV
pitch_train = '/content/drive/MyDrive/port_coruna/pitch_train.csv'
df = pd.read_csv(pitch_train)
x = df[['h_s', 't_p', 'dir', 'wind_speed', 'wind_dir', 'h_0', 'h_sm', 'length', 'breath']]
y = df[['mov_avg','mov_max','mov_sig']]

# Se crea la instancia (objeto específico del modelo) y se ajusta el modelo a los datos
model = RandomForestRegressor()
model.fit(x, y)
prediction_rf = model.predict(x)
r2 = r2_score(y, prediction_rf)

# Se realizan predicciones del modelo y se muestra

plt.scatter(y, prediction_rf)
plt.xlabel('Cabeceo de la embarcación (real)')
plt.ylabel('Cabeceo de la embarcación (Predicción)')
plt.show()
print("Número de árboles en el bosque:", model.n_estimators)
print(r2)